name: DockerHub

on:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 20 1 * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Node 15 Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: node15/Dockerfile
          push: true
          tags: splintnet/alpine-node:node15
      -
        name: Node 16 Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: Dockerfile
          push: true
          tags: splintnet/alpine-node:latest,splintnet/alpine-php:node16
