name: DockerHub

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 20 1 * *"

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Node 22
        uses: docker/build-push-action@v6
        with:
          context: ./
          platforms: linux/amd64,linux/arm64
          file: node22/Dockerfile
          push: true
          tags: splintnet/alpine-node:latest,splintnet/alpine-node:node22,splintnet/alpine-node:22

      - name: Node 19
        uses: docker/build-push-action@v6
        with:
          context: ./
          platforms: linux/amd64,linux/arm64
          file: node19/Dockerfile
          push: true
          tags: splintnet/alpine-node:node19,splintnet/alpine-node:19
